name: run config map changes
on:
  push:
    paths:
      - 'configmap/**'

  
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ''
          fileOutput: ''
      - name: test
        run: |
          
          echo '${{ steps.file_changes.outputs.files}}'
          
      - name: test java changes
        if: contains(steps.file_changes.outputs.files,'.java')  
        run: echo "Hello java changes"  
         
