name: deploy to dev Auto 
on:
  pull_request:
  push:
    branches:
      - master
      - '*_Release'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "deployment to dev is completed"
