name: File Changes Action

on: push

jobs:
  build:
    env:
      IS_TMPL_FILES_CHANGED: "false"  
    runs-on: ubuntu-latest
    steps:
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.abc.outputs.all }}"
          env.IS_TMPL_FILES_CHANGED = "${{ steps.abc.outputs.all }}"
          echo "IS_TMPL_FILES_CHANGED:"
          echo ${{env.IS_TMPL_FILES_CHANGED}}
          echo "Added:"
          echo "${{ steps.abc.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.abc.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.abc.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.abc.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"
