name: File Changes Action

on: push

jobs:
  build:
    env:
      IS_TMPL_FILES_CHANGE:  "false"
      IS_NON_TMPL_FILES_CHANGE:  "false"  
      POM_VERSION: ""  
    runs-on: ubuntu-latest
    steps:
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          
      - name: Non Tmpl file changes
        if: contains(steps.abc.outputs.all,'.properties') ||  contains(steps.abc.outputs.all,'.java')
        run: |
         echo "properties or java file canges"
         echo ::set-env name=IS_NON_TMPL_FILES_CHANGE::true
          
      - name: Tmpl file changes
        if: contains(steps.abc.outputs.all,'.tmpl')
        run: |
         echo "tmpl file canges"
         echo ::set-env name=IS_TMPL_FILES_CHANGE::true
        
      - name: Printing
        run: |
          echo "tmpl file changes: ${IS_TMPL_FILES_CHANGE}"
          echo "non tmpl file changes: ${IS_NON_TMPL_FILES_CHANGE}"
          echo "comparision  "
          echo contains(IS_NON_TMPL_FILES_CHANGE,'true')
   
      - name: Get POM version
        run : |
            git clone https://github.com/das-devi/SPRINGRESTAPP01.git
            cd SPRINGRESTAPP01      
            POM_VERSION=`cat variables`
            echo "pom version is ${POM_VERSION}"
            POM_VERSION=$(<variables)
            echo "pom version is ${POM_VERSION}"
            
            echo ::set-env name=POM_VERSION::$(<variables)
            
      - name: Print pom version
        run: echo " POM version is ${POM_VERSION} ext files ${IS_TMPL_FILES_CHANGE}"
         
             
          
    
       
