name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend: [eclipse, swi-prolog]
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world! ${{ matrix.backend }}
    - name: Run a one-line-one script
      run: echo Hello, world! ${{ matrix.backend }}
    
