name: Github Actions Example

on:
  pull_request:
  push:
    branches: 
      - master
      - develop

jobs:
  build:
    env: 
      userName: "das.angular@gmail.com"  
    name: Running Units Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Echo
      run: echo Hello, world! ${{env.userName}}
