name: Github Actions Example

on:
  pull_request:
  push:
    branches: 
      - master
      - develop

jobs:
  build:
    env: 
      userName: ${{secrets.MAIL_USERNAME}}  
    name: Running Units Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Echo
      if: env.userName == 'dass.angular@gmail.com'
      run: echo Hello, world! ${{env.userName}}
