name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend: [rudra-dev, rudra-test]
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line eclipse script
      if: ${{secrets.MAIL_USERNAME}} == 'das.angular@gmail.com'
      run: echo Hello, world! ${{ matrix.backend }}

