name: run configmap manually 
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter K8 nams-space (default to dev)'
        required: false
        default: 'dev'
     

jobs:
  run-configmap:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "configmap creation in rudra-${{ github.event.inputs.name }} is completed!"
